version: "3"

services:
    db:
        container_name: todo-list-database
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - ./postgres_db:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: mYPa55exAmple!
            POSTGRES_DB: todo-list-db
